/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-11-11 04:45:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.security;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class donate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("jar:file:/C:/backend-workspace/alertravel_kjw/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project_alertravel/WEB-INF/lib/spring-security-taglibs-5.0.7.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1532606274000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.0.7.RELEASE.jar", Long.valueOf(1693959208075L));
    _jspx_dependants.put("jar:file:/C:/backend-workspace/alertravel_kjw/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project_alertravel/WEB-INF/lib/spring-webmvc-5.0.7.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1528782246000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.0.7.RELEASE.jar", Long.valueOf(1695082487079L));
    _jspx_dependants.put("jar:file:/C:/backend-workspace/alertravel_kjw/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project_alertravel/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/security/../layouts/header1.jsp", Long.valueOf(1699439314652L));
    _jspx_dependants.put("/WEB-INF/views/security/../layouts/footer1.jsp", Long.valueOf(1699576743595L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1693959208435L));
    _jspx_dependants.put("jar:file:/C:/backend-workspace/alertravel_kjw/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project_alertravel/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <title>Alertravel</title>\r\n");
      out.write("    <meta\r\n");
      out.write("      name=\"viewport\"\r\n");
      out.write("      content=\"width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0\"\r\n");
      out.write("    />\r\n");
      out.write("    <!-- user-scalable 을 사용하지 않는 디바이스를 위해, maximun-scale/minimum-scale 설정을 하는 것입니다-->\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Open Graph (Facebook, Linkedin) -->\r\n");
      out.write("    <!-- https://ourcodeworld.com/public-media/articles/articleocw-56d1a6901b773.png -->\r\n");
      out.write("    <meta property=\"og:type\" content=\"website\" />\r\n");
      out.write("    <!-- https://ogp.me/#types -->\r\n");
      out.write("    <meta property=\"og:title\" content=\"Alertravel\" />\r\n");
      out.write("    <meta\r\n");
      out.write("      property=\"og:description\"\r\n");
      out.write("      content=\"여러분의 안전한 여행을 응원하는 Alertravel입니다.\"\r\n");
      out.write("    />\r\n");
      out.write("    <meta property=\"og:site_name\" content=\"Alertravel\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- twitter card (Twitter) -->\r\n");
      out.write("    <!-- https://csharpcorner-mindcrackerinc.netdna-ssl.com/article/twitter-cards-implementation-with-websites/Images/summary_card_tweet.png -->\r\n");
      out.write("    <meta name=\"twitter:card\" content=\"summary\" />\r\n");
      out.write("    <!-- card 종류: summary, photo, player -->\r\n");
      out.write("    <meta name=\"twitter:title\" content=\"Alertravel\" />\r\n");
      out.write("    <meta\r\n");
      out.write("      name=\"twitter:description\"\r\n");
      out.write("      content=\"여러분의 안전한 여행을 응원하는 Alertravel입니다.\"\r\n");
      out.write("    />\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!-- 일반적인 fabicon 설정 -->\r\n");
      out.write("    <link rel=\"icon\" href=\"img/alertravelicon.ico\" />\r\n");
      out.write("    <!-- 아이폰용 fabicon 설정 -->\r\n");
      out.write("    <link rel=\"apple-touch-icon\" href=\"img/alertravelicon.ico\" />\r\n");
      out.write("    <!-- 인터넷 익스플러오용 fabicon 설정-->\r\n");
      out.write("    <link rel=\"short icon\" type=\"image/x-icon\" href=\"img/alertravelicon.ico\" />\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/normalize.css\" />\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/main.css\" />\r\n");
      out.write("    \r\n");
      out.write("    <!-- https://fontawesome.com/start -->\r\n");
      out.write("    <script\r\n");
      out.write("      src=\"https://kit.fontawesome.com/f1def33959.js\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    ></script>\r\n");
      out.write("    <!-- Spoca Han Sans Neo: https://spoqa.github.io/spoqa-han-sans/ko-KR/ -->\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSansNeo.css\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      type=\"text/css\"\r\n");
      out.write("    />\r\n");
      out.write("    <link href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/style.css\" />\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <header>\r\n");
      out.write("      <div class=\"inner\">\r\n");
      out.write("        <div class=\"head-container\">\r\n");
      out.write("          <div class=\"head-brand\">\r\n");
      out.write("            <a href=\"#\">Alertravel</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"head-blog\">\r\n");
      out.write("              여러분의 여행을 응원합니다.\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <!-- 메인 이미지 섹션 -->\r\n");
      out.write("    <section class=\"main\">\r\n");
      out.write("      <div class=\"main-container\">\r\n");
      out.write("        <div class=\"inner\">\r\n");
      out.write("          <div class=\"title-container\">\r\n");
      out.write("            <div class=\"title\">안전한 여행</div>\r\n");
      out.write("            <div class=\"message\">\r\n");
      out.write("              해외국가의 단계별 여행 경보를 알려드립니다.<br />\r\n");
      out.write("              여러분의 여행 발자취를<br />\r\n");
      out.write("              이곳에 남기어 같이 공유해주세요.<br />\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section>\r\n");
      out.write("      <div class=\"inner\">\r\n");
      out.write("        <div class=\"skill-container\">\r\n");
      out.write("          <div class=\"skill\">\r\n");
      out.write("            <i class=\"fas fa-info skill-icon\"></i>\r\n");
      out.write("            <div class=\"skill-title\">\r\n");
      out.write("              <div class=\"skill-name\">해외안전정보</div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"skill\">\r\n");
      out.write("            <i class=\"fas fa-comments skill-icon\"></i>\r\n");
      out.write("            <div class=\"skill-title\">\r\n");
      out.write("              <div class=\"skill-name\">소통마당</div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"skill\">\r\n");
      out.write("            <i class=\"fas fa-route skill-icon\"></i>\r\n");
      out.write("            <div class=\"skill-title\">\r\n");
      out.write("              <div class=\"skill-name\">편의기능</div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"skill\">\r\n");
      out.write("            <i class=\"fas fa-money-check skill-icon\"></i>\r\n");
      out.write("            <div class=\"skill-title\">\r\n");
      out.write("              <div class=\"skill-name\">후원하기</div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<div class=\"donate_title\">\r\n");
      out.write("	<h1><i class=\"fas fa-money-check skill-icon\"> 후원하기</i></h1>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container mt-5\">\r\n");
      out.write("	<div class=\"row justify-content-center\">\r\n");
      out.write("		<div class=\"col-md-8\">\r\n");
      out.write("			<div class=\"card border-0\"> <!-- 외부 선 제거 -->\r\n");
      out.write("				<div class=\"card-body\">\r\n");
      out.write("					<form action=\"payment\" method=\"post\"> <!-- submit 버튼 누르면 이동할 곳 -->\r\n");
      out.write("						<input type=\"hidden\" name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.parameterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("						\r\n");
      out.write("							<h3><br>후원자 정보<br></h3>\r\n");
      out.write("							\r\n");
      out.write("							<!-- 후원자 개인 정보 입력 -->\r\n");
      out.write("							<div class=\"form-group\" id=\"nameInput\">\r\n");
      out.write("								<label for=\"name\">성명</label> \r\n");
      out.write("								<input type=\"text\" name=\"name\" class=\"form-control\" placeholder=\"성명 입력\">\r\n");
      out.write("							</div>\r\n");
      out.write("							\r\n");
      out.write("							<br>\r\n");
      out.write("							\r\n");
      out.write("							<div class=\"form-group\" id=\"birthdayInput\">\r\n");
      out.write("								<label for=\"birthday\">생년월일</label>\r\n");
      out.write("								<input type=\"text\" name=\"birthday\" class=\"form-control\" placeholder=\"생년월일 6자리 입력\">\r\n");
      out.write("								<pre>※만 14세 미만의 경우, 후원이 불가능합니다.※</pre>\r\n");
      out.write("							</div>\r\n");
      out.write("							\r\n");
      out.write("							<br>\r\n");
      out.write("							\r\n");
      out.write("							<div class=\"form-group\" id=\"phoneInput\">\r\n");
      out.write("								<label for=\"phone\">휴대폰 번호</label>\r\n");
      out.write("								<input type=\"text\" name=\"phone\" class=\"form-control\" placeholder=\"휴대펀 번호 입력('-' 제외)\">\r\n");
      out.write("							</div>\r\n");
      out.write("							\r\n");
      out.write("							<br>\r\n");
      out.write("							\r\n");
      out.write("							<div class=\"form-group\" id=\"emailInput\">\r\n");
      out.write("								<label for=\"email\">이메일</label>\r\n");
      out.write("								<input type=\"text\" name=\"email\" class=\"form-control\" placeholder=\"이메일 주소 입력\">\r\n");
      out.write("							</div>\r\n");
      out.write("							\r\n");
      out.write("							<br>\r\n");
      out.write("							<hr color=\"#F0A07B\">\r\n");
      out.write("							<br>\r\n");
      out.write("						\r\n");
      out.write("							<!-- 후원 국가 선택창 -->\r\n");
      out.write("							<label for=\"country\"><b><h5>후원 국가 선택</h5></b></label>\r\n");
      out.write("							<select class=\"form-control\" name=\"country\" id=\"donationCountry\">\r\n");
      out.write("								<option value=\"noCountry\">== 국가 선택 ==</option>\r\n");
      out.write("								<option value=\"nation1\">국가 1</option>\r\n");
      out.write("								<option value=\"nation2\">국가 2</option>\r\n");
      out.write("								<option value=\"nation3\">국가 3</option>\r\n");
      out.write("								<option value=\"nation4\">국가 4</option>\r\n");
      out.write("								<option value=\"nation5\">국가 5</option>\r\n");
      out.write("								<option value=\"nation6\">국가 6</option>\r\n");
      out.write("								<option value=\"nation7\">국가 7</option>\r\n");
      out.write("								<option value=\"nation8\">국가 8</option>\r\n");
      out.write("								<option value=\"nation9\">국가 9</option>\r\n");
      out.write("								<option value=\"nation10\">국가 10</option>\r\n");
      out.write("							</select> \r\n");
      out.write("							\r\n");
      out.write("							<br>\r\n");
      out.write("							\r\n");
      out.write("							<!-- 후원 금액 선택창 -->\r\n");
      out.write("							<label for=\"amount\"><b><h5>후원 금액 선택</h5></b></label>\r\n");
      out.write("							<select class=\"form-control\" name=\"amount\" id=\"donationAmount\">							\r\n");
      out.write("								<option value=\"noAmount\">== 금액 선택 ==</option>\r\n");
      out.write("								<option value=\"10000\">10,000원</option>\r\n");
      out.write("								<option value=\"30000\">30,000원</option>\r\n");
      out.write("								<option value=\"50000\">50,000원</option>\r\n");
      out.write("								<option value=\"100000\">100,000원</option>\r\n");
      out.write("								<option value=\"300000\">300,000원</option>\r\n");
      out.write("							</select>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label for=\"message\"><b><h5>응원 메시지</h5></b></label>\r\n");
      out.write("							<textarea class=\"form-control\" name=\"message\" rows=\"3\"\r\n");
      out.write("								placeholder=\"응원 메시지를 남겨주세요\"></textarea>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<br>\r\n");
      out.write("						<hr color=\"#F0A07B\">\r\n");
      out.write("						<br>\r\n");
      out.write("						\r\n");
      out.write("						<!-- 후원 요약 정보를 보여줄 컨테이너 -->\r\n");
      out.write("						<div id=\"summaryContainer\" style=\"display: none;\">\r\n");
      out.write("							<label for=\"summary\"><b><h5>후원 요약</h5></b></label>\r\n");
      out.write("								<p id=\"summaryText\"></p>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<button type=\"submit\" class=\"btn btn-block\">후원하기</button>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS and dependencies -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("  // 함수를 만들어 국가 및 후원 금액에 대한 요약을 업데이트\r\n");
      out.write("  function updateSummary() {\r\n");
      out.write("    var summaryContainer = document.getElementById('summaryContainer');\r\n");
      out.write("    var summaryText = document.getElementById('summaryText');\r\n");
      out.write("    \r\n");
      out.write("    // 선택한 국가 및 후원 금액 가져오기\r\n");
      out.write("    var selectedCountry = document.getElementById('donationCountry').\r\n");
      out.write("    						options[document.getElementById('donationCountry').selectedIndex].text;\r\n");
      out.write("    var selectedAmount = document.getElementById('donationAmount').\r\n");
      out.write("    						options[document.getElementById('donationAmount').selectedIndex].text;\r\n");
      out.write("\r\n");
      out.write("    // 항상 요약을 표시\r\n");
      out.write("    summaryContainer.style.display = 'block';\r\n");
      out.write("    summaryText.innerText = \"선택 국가: \" + selectedCountry +\r\n");
      out.write("                            \"\\n후원 금액: \" + selectedAmount;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  // 후원 금액 변경 시 이벤트 처리\r\n");
      out.write("  document.getElementById('donationAmount').addEventListener('change', function() {\r\n");
      out.write("    updateSummary();\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("  // 국가 변경 시 이벤트 처리\r\n");
      out.write("  document.getElementById('donationCountry').addEventListener('change', function() {\r\n");
      out.write("    updateSummary();\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("  // 초기 로딩 시 실행\r\n");
      out.write("  window.addEventListener('load', function() {\r\n");
      out.write("    // 처음에 숨겨둔 요약 컨테이너를 표시\r\n");
      out.write("    document.getElementById('summaryContainer').style.display = 'block';\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("	.donate_title {\r\n");
      out.write("		padding: 50px 300px 50px; /* 패딩: 위, 좌우, 아래 */\r\n");
      out.write("	    background-color: #F0A07B;\r\n");
      out.write("    	border-color: #F0A07B;\r\n");
      out.write("		color: white;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("<style>\r\n");
      out.write("	.btn {\r\n");
      out.write("	    background-color: #F0A07B;\r\n");
      out.write("    	border-color: #F0A07B;\r\n");
      out.write("		color: white;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer class=\"p-3 footer mt-5\">\r\n");
      out.write("	<div class=\"inner\">\r\n");
      out.write("		<div class=\"footer-message\">여러분의 안전한 여행을 늘 희망합니다.</div>\r\n");
      out.write("		<div class=\"footer-contact\">컨택: jeonsm6@gmail.com</div>\r\n");
      out.write("		<div class=\"footer-copyright\">Copyright 2023 © All rights\r\n");
      out.write("			reserved.</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
