/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-11-15 05:35:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.donate;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class payment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"https://code.jquery.com/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<!-- iamport.payment.js -->\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"https://cdn.iamport.kr/js/iamport.payment-1.2.0.js\"></script>\r\n");
      out.write("<!-- axios -->\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"https://unpkg.com/axios/dist/axios.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");

    // 폼에서 전달된 "donationAmount" 파라미터 받기
    String donationAmount = request.getParameter("donationAmount");

    // 받아온 값이 null이 아니라면 출력
    if (donationAmount != null) {
        out.println("선택한 금액: " + donationAmount);
    } else {
        out.println("금액이 선택되지 않았습니다.");
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("        var IMP = window.IMP; \r\n");
      out.write("        IMP.init(\"imp81120017\"); \r\n");
      out.write("      \r\n");
      out.write("        var today = new Date();   \r\n");
      out.write("        var hours = today.getHours(); // 시\r\n");
      out.write("        var minutes = today.getMinutes();  // 분\r\n");
      out.write("        var seconds = today.getSeconds();  // 초\r\n");
      out.write("        var milliseconds = today.getMilliseconds();\r\n");
      out.write("        var makeMerchantUid = hours +  minutes + seconds + milliseconds;\r\n");
      out.write("        \r\n");
      out.write("        function requestPay1() {\r\n");
      out.write("            IMP.request_pay({\r\n");
      out.write("                pg: 'kcp', // pg사\r\n");
      out.write("                pay_method: 'card', // 결제 수단\r\n");
      out.write("                merchant_uid: \"ORD20231111-0000001\", // 주문번호\r\n");
      out.write("                name: 'kcp 결제창', // 상품 이름\r\n");
      out.write("                merchant_uid: 'ORD20231114-000001',\r\n");
      out.write("                amount: 10000, // 총 결제 금액\r\n");
      out.write("                buyer_name: '아임포트 기술지원팀', // 구매자 이름\r\n");
      out.write("                buyer_tel: '010-1234-5678', // 구매자 전화번호\r\n");
      out.write("                buyer_email: 'Iamport@chai.finance' // 구매자 이메일\r\n");
      out.write("            }, function (rsp) { // callback\r\n");
      out.write("                if (rsp.success) {\r\n");
      out.write("                    console.log(rsp);\r\n");
      out.write("                } else {\r\n");
      out.write("                    console.log(rsp);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        function requestPay2() {\r\n");
      out.write("            IMP.request_pay({\r\n");
      out.write("                pg : 'kakaopay',\r\n");
      out.write("                pay_method : 'card',\r\n");
      out.write("                name : '카카오페이 결제창',\r\n");
      out.write("                merchant_uid : 'ORD20231114-000002',\r\n");
      out.write("                amount : 222222,\r\n");
      out.write("                buyer_email : 'Iamport@chai.finance',\r\n");
      out.write("                buyer_name : '아임포트 기술지원팀',\r\n");
      out.write("                buyer_tel : '010-1234-5678',\r\n");
      out.write("            }, function (rsp) { // callback\r\n");
      out.write("                if (rsp.success) {\r\n");
      out.write("                    console.log(rsp);\r\n");
      out.write("                } else {\r\n");
      out.write("                    console.log(rsp);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function requestPay3() {\r\n");
      out.write("            IMP.request_pay({\r\n");
      out.write("                pg : 'tosspay',\r\n");
      out.write("                pay_method : 'card',\r\n");
      out.write("                name : '토스페이 결제창',\r\n");
      out.write("                merchant_uid : 'ORD20231114-000003',\r\n");
      out.write("                amount : 333333,\r\n");
      out.write("                buyer_email : 'Iamport@chai.finance',\r\n");
      out.write("                buyer_name : '아임포트 기술지원팀',\r\n");
      out.write("                buyer_tel : '010-1234-5678',\r\n");
      out.write("            }, function (rsp) { // callback\r\n");
      out.write("                if (rsp.success) {\r\n");
      out.write("                    console.log(rsp);\r\n");
      out.write("                } else {\r\n");
      out.write("                    console.log(rsp);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("<title>Sample Payment</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<button onclick=\"requestPay1()\">kcp 결제하기</button>\r\n");
      out.write("	<!-- 결제하기 버튼 생성 -->\r\n");
      out.write("	<button onclick=\"requestPay2()\">카카오페이 결제하기</button>\r\n");
      out.write("	<!-- 결제하기 버튼 생성 -->\r\n");
      out.write("	<button onclick=\"requestPay3()\">토스페이 결제하기</button>\r\n");
      out.write("	<!-- 결제하기 버튼 생성 -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
